spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ragcreator
    username: ragcreator
    password: ragcreatorpassword
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
