import httpx

from rag_worker.contracts.pdf_interpret import (
    PdfInterpretVisualRequest,
    PdfInterpretVisualResponse,
    VisualInterpretation,
    VisualBudgetResult,
    VisualUsage,
    WorkerError
)
from rag_worker.contracts.base import WorkerErrorResponse, WorkerErrorDetail

async def interpret_visual_and_callback(request: PdfInterpretVisualRequest, callback_url: str) -> None:
    try:
        response = interpret_visual_sync(request)
        async with httpx.AsyncClient() as client:
            await client.post(callback_url, json=response.model_dump())
    except Exception as e:
        error_resp = WorkerErrorResponse(
            requestId=request.requestId,
            error=WorkerErrorDetail(
                code="pdf_interpret_visual_failed",
                message=str(e),
                retryable=False,
                safeDetails={"workerContractVersion": "worker.pdf.interpret_visual.response.v1"}
            )
        )
        async with httpx.AsyncClient() as client:
            await client.post(callback_url, json=error_resp.model_dump())

def interpret_visual_sync(request: PdfInterpretVisualRequest) -> PdfInterpretVisualResponse:
    interpretations = []
    
    # Mock behavior processing requested items
    for idx, item in enumerate(request.items):
        if idx >= request.budget.maxItems:
            break

        # Generate mock interpretation
        interpretation = VisualInterpretation(
            interpretationId=f"vis_mock_{idx}",
            elementId=item.elementId,
            assetId=item.assetId,
            status="completed",
            interpretationText="Mock interpretation text generated by mock-vision-interpreter",
            structuredText={
                "kind": "visual_interpretation_v1",
                "summary": "Mock summary",
                "detectedText": item.detectedText,
                "keyFacts": ["Fact 1", "Fact 2"]
            },
            provider=request.provider,
            model=request.model,
            promptVersion=request.promptVersion,
            inputHash=f"sha256:mock:{item.assetId}",
            confidence=0.85,
            usage=VisualUsage(
                inputTokensEstimate=150,
                outputTokensEstimate=50,
                cacheHit=False
            ),
            sourceLocator=item.sourceLocator
        )
        interpretations.append(interpretation)

    budget_result = VisualBudgetResult(
        itemsRequested=len(request.items),
        itemsProcessed=len(interpretations),
        itemsSkipped=len(request.items) - len(interpretations),
        limitHit=len(request.items) > request.budget.maxItems
    )

    return PdfInterpretVisualResponse(
        requestId=request.requestId,
        workspaceId=request.workspaceId,
        documentId=request.documentId,
        runId=request.runId,
        interpretations=interpretations,
        budget=budget_result,
        warnings=[]
    )
