ALTER TABLE workspaces 
ADD COLUMN slug VARCHAR(255) UNIQUE,
ADD COLUMN owner_user_id UUID REFERENCES users(id),
ADD COLUMN settings JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
